image: cirrusci/flutter

stages:
    - build
    - test
    - deploy

build-web:
    stage: build
    tags: 
        - linux
    script:
        - flutter build web

build-android:
    image: cirrusci/flutter
    stage: build
    tags: 
        - android
    script:
        - flutter build appbundle

build-ios:
    stage: build
    tags: 
        - iOS
    script:
        # Hopefully this works :D
        - flutter build ipa
    when: manual

test-ios:
    stage: test
    tags: 
        - iOS
    script:
        - flutter test
    when: manual
    dependencies:
      - build-ios

test-linux:
    stage: test
    tags: 
        - linux
    script:
        - flutter test
    dependencies:
      - build-web
      - build-android

# TODO: deploy

