# SPDX-FileCopyrightText: 2022 iDichotic+ Authors <https://dichotic.app>
#
# SPDX-License-Identifier: CC0-1.0

image: cirrusci/flutter

stages:
    - validate
    - build
    - test
    - deploy

include:
    - "/.gitlab/ci/.gitlab-android.yml"
    - "/.gitlab/ci/.gitlab-ios.yml"
    - "/.gitlab/ci/.gitlab-linux.yml"
    - "/.gitlab/ci/.gitlab-web.yml"
    - "/.gitlab/ci/.gitlab-license.yml"

variables:
    PUB_CACHE: $CI_PROJECT_DIR/.pub-cache
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

cache:
    paths:
        - $CI_PROJECT_DIR/.gradle/
        - $CI_PROJECT_DIR/.pub-cache/
        - $CI_PROJECT_DIR/.dart_tool/
        - $CI_PROJECT_DIR/.flutter-plugins/
        - $CI_PROJECT_DIR/.flutter-plugins-dependencies/

# TODO: deploy

