# SPDX-FileCopyrightText: 2022 iDichotic+ Authors <https://dichotic.app>
#
# SPDX-License-Identifier: CC0-1.0

template-arb-file: intl_en.arb
arb-dir: assets/l10n
output-localization-file: l10n.dart
preferred-supported-locales: ["en"]
output-class: L10n