name: Test

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            id: Linux
          - os: macos-latest
            id: macOS
          - os: windows-latest
            id: Windows

    # a push event from the origin repo, or a PR from external repo
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}

    name: Test ${{ matrix.config.id }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - run: flutter test
