# SPDX-FileCopyrightText: 2022 iDichotic+ Authors <https://dichotic.app>
#
# SPDX-License-Identifier: CC0-1.0

name: Validate

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.2.0
