# SPDX-FileCopyrightText: 2022 iDichotic+ Authors <https://dichotic.app>
#
# SPDX-License-Identifier: CC0-1.0

name: Validate

on:
  push:
  pull_request:

jobs:
  validate:

    # a push event from the origin repo, or a PR from external repo
    if: ${{ github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}

    runs-on: ubuntu-latest
    steps:
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1.2.0
