# SPDX-FileCopyrightText: 2022 iDichotic+ Authors <https://dichotic.app>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

build-web:
  stage: build
  tags:
    - linux
  script:
    - flutter build web
