# SPDX-FileCopyrightText: 2022 iDichotic+ Authors <https://dichotic.app>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

license-check:
  stage: validate
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint